name: CD Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*' # Trigger cuando se pushea un tag (ej. v1.0.0)

permissions:
  contents: write # Necesario para crear el release

jobs:
  create-github-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Nueva versión liberada: ${{ github.ref_name }}
            Este release fue generado automáticamente por el pipeline de CD.
          draft: false
          prerelease: false
